### PR TITLE
Allow native application OAuth 2 client flow

### PR DESCRIPTION
**Pull request by ahills**
The command line does not provide a way to use the standard
`--noauth_local_webserver` option provided by the `oauth2client` library
for the `tools.run_flow()` method. Integrates the provided
`ArgumentParser` instance in the recommended way:

https://oauth2client.readthedocs.io/en/latest/source/oauth2client.tools.html#oauth2client.tools.run_flow

Also allows offline use when just generating XML.

### CODE REVIEW

**Comment by ahills** [comment]
@mesozoic, I'm not sure exactly how to fit tests for a workflow change into the existing test framework. I also can't see whether any Travis runs have launched, but the existing tests pass on my local machine.

**Comment by mesozoic** [comment]
I've never needed this flag to authenticate, but I've only ever run this locally on macOS. I agree the lack of any sort of integration test is troublesome (see #23 for an example of something I wish I'd caught). Can you help me understand and reproduce the failure you were encountering before making this change?

**Comment by mesozoic** [comment]
(By the way, and I should've opened with this, thank you for all of the notes and pull requests! It's wonderful to see others taking an interest in this side project of mine.)

**Comment by ahills** [comment]
When I created the credentials in the Google API Console, I chose "Desktop app" as the application type, as it seemed most appropriate of the options. I wasn't able to successfully authenticate with a GSuite account using a separate SSO integration (one of the many possible Google account experiences) via the loopback method, so I wanted to provide the `--noauth_local_webserver` option.

Providing a reproducer for this exact scenario would be challenging, but if we take the ability to control the `oauth2client` library as a given goal, using its provided argument parser seems like a more or less straightforward choice. The method I used here has some drawbacks; perhaps providing an argument to pass through arguments would be more appropriate, and keep the help output cleaner—or maybe the PR should instead be a [migration to the `google-auth` library](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

While my Google credentials weren't functioning, I also discovered that I couldn't easily exercise all of the offline options, which is why I changed the flow in `main()`.

(It's a particularly useful side project for Gmail accounts with dozens of similar filters; thank you for publishing it.)

**Pull request closed without merging**
